FROM nginx:stable-alpine

COPY infrastructure/nginx/nginx.conf.prod /etc/nginx/nginx.conf.prod

CMD ["/bin/sh", "-c", "envsubst '${AUTH_SERVICE_URL} ${PRODUCT_SERVICE_URL} ${ORDER_SERVICE_URL} ${PAYMENT_SERVICE_URL} ${CHAT_SERVICE_URL}' < /etc/nginx/nginx.conf.prod > /etc/nginx/nginx.conf && nginx -t && nginx -g 'daemon off;'"]